name: german-odoo-directory
region: fra
services:
- name: web
  github:
    repo: YOUR_GITHUB_USERNAME/german-odoo-directory
    branch: main
    deploy_on_push: true
  build_command: npm install && npm run build
  run_command: npx serve -s dist -l tcp://0.0.0.0:8080
  source_dir: /
  environment_slug: node-js
  instance_size_slug: basic-xxs
  instance_count: 1
  http_port: 8080
  routes:
  - path: /
  envs:
  - key: NODE_ENV
    value: production
    type: GENERAL
  - key: SUPABASE_URL
    value: "${SUPABASE_URL}"
    type: SECRET
  - key: SUPABASE_ANON_KEY
    value: "${SUPABASE_ANON_KEY}"
    type: SECRET